### ISSUE TITLE
CJP #3 - Home UI

### ISSUE THREAD

**Issue by chrisjpounds** [sfisque/eCactus-latticeware#26] opened 2020-02-14 02:13 UTC
Make Home Screen look like corresponding tab in attached file.
[Exelon eCalendar Requirements Log and Proposed UI layout (2-9-20).xlsx](https://github.com/sfisque/eCactus-latticeware/files/4202332/Exelon.eCalendar.Requirements.Log.and.Proposed.UI.layout.2-9-20.xlsx)

**Comment by sfisque** [comment] 2020-02-15 19:56
duplicate of #21

**Closed by sfisque** 2020-02-15 19:56 UTC
